issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fohte/.github:ref:refs/heads/.+$
claim_pattern:
  job_workflow_ref: ^fohte/.github/\.github/workflows/test\.yml@[^@]+$
repositories:
  - .github
permissions:
  contents: write
