issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fohte/blog-publisher:ref:refs/heads/.+$
claim_pattern:
  job_workflow_ref: ^fohte/blog-publisher/\.github/workflows/test\.yml@[^@]+$
repositories:
  - blog-publisher
permissions:
  contents: write
