issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fohte/bms-dashtray:pull_request$
claim_pattern:
  job_workflow_ref: ^fohte/bms-dashtray/\.github/workflows/renovate-copier\.yml@[^@]+$
repositories:
  - bms-dashtray
permissions:
  contents: write
