issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fohte/bms-dashtray:ref:refs/heads/.+$
claim_pattern:
  job_workflow_ref: ^fohte/bms-dashtray/\.github/workflows/test\.yml@[^@]+$
repositories:
  - bms-dashtray
permissions:
  contents: write
