issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fohte(@[0-9]+)?/contracts(@[0-9]+)?:ref:refs/heads/.+$
claim_pattern:
  job_workflow_ref: ^fohte/contracts/\.github/workflows/test\.yml@[^@]+$
repositories:
  - contracts
permissions:
  contents: write
