issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fohte/contracts:pull_request$
claim_pattern:
  job_workflow_ref: ^fohte/contracts/\.github/workflows/renovate-copier\.yml@[^@]+$
repositories:
  - contracts
permissions:
  contents: write
