issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fohte(@11088009)?/contracts(@1243002152)?:pull_request$
claim_pattern:
  job_workflow_ref: ^fohte/contracts/\.github/workflows/renovate-copier\.yml@[^@]+$
repositories:
  - contracts
permissions:
  contents: write
