issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fohte/ddr-score-manager:ref:refs/heads/.+$
claim_pattern:
  job_workflow_ref: ^fohte/ddr-score-manager/\.github/workflows/test\.yml@[^@]+$
repositories:
  - ddr-score-manager
permissions:
  contents: write
