issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fohte/dotfiles:pull_request$
claim_pattern:
  job_workflow_ref: ^fohte/dotfiles/\.github/workflows/renovate-copier\.yml@[^@]+$
repositories:
  - dotfiles
permissions:
  contents: write
