issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fohte/generic-boilerplate:pull_request$
claim_pattern:
  job_workflow_ref: ^fohte/generic-boilerplate/\.github/workflows/sync-generated-to-template\.yml@[^@]+$
repositories:
  - generic-boilerplate
permissions:
  contents: write
