issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fohte/gmail-filters:pull_request$
claim_pattern:
  job_workflow_ref: ^fohte/gmail-filters/\.github/workflows/renovate-copier\.yml@[^@]+$
repositories:
  - gmail-filters
permissions:
  contents: write
