issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fohte(@11088009)?/gmail-filters(@414528684)?:ref:refs/heads/.+$
claim_pattern:
  job_workflow_ref: ^fohte/gmail-filters/\.github/workflows/format\.yml@[^@]+$
repositories:
  - gmail-filters
permissions:
  contents: write
