issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fohte/gmail-filters:ref:refs/heads/master$
claim_pattern:
  job_workflow_ref: ^fohte/gmail-filters/\.github/workflows/boilerplate-update\.yml@[^@]+$
repositories:
  - gmail-filters
permissions:
  contents: write
  pull_requests: write
  workflows: write
