issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fohte/homebrew-tap:ref:refs/heads/.+$
claim_pattern:
  job_workflow_ref: ^fohte/homebrew-tap/\.github/workflows/test\.yml@[^@]+$
repositories:
  - homebrew-tap
permissions:
  contents: write
