issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fohte(@[0-9]+)?/infra(@[0-9]+)?:ref:refs/heads/master$
claim_pattern:
  job_workflow_ref: ^fohte/infra/\.github/workflows/boilerplate-update\.yml@[^@]+$
repositories:
  - infra
permissions:
  contents: write
  pull_requests: write
  workflows: write
