issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fohte(@[0-9]+)?/renovate-config(@[0-9]+)?:ref:refs/heads/.+$
claim_pattern:
  job_workflow_ref: ^fohte/renovate-config/\.github/workflows/sync-generic-boilerplate\.yml@[^@]+$
repositories:
  - renovate-config
permissions:
  contents: write
