issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fohte/service-kit:pull_request$
claim_pattern:
  job_workflow_ref: ^fohte/service-kit/\.github/workflows/renovate-copier\.yml@[^@]+$
repositories:
  - service-kit
permissions:
  contents: write
