issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fohte(@[0-9]+)?/service-kit(@[0-9]+)?:ref:refs/heads/.+$
claim_pattern:
  job_workflow_ref: ^fohte/service-kit/\.github/workflows/test\.yml@[^@]+$
repositories:
  - service-kit
permissions:
  contents: write
