issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fohte/slack-bot:pull_request$
claim_pattern:
  job_workflow_ref: ^fohte/slack-bot/\.github/workflows/renovate-copier\.yml@[^@]+$
repositories:
  - slack-bot
permissions:
  contents: write
