issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fohte/specs:ref:refs/heads/.+$
claim_pattern:
  job_workflow_ref: ^fohte/specs/\.github/workflows/test\.yml@[^@]+$
repositories:
  - specs
permissions:
  contents: write
