issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fohte/tq:ref:refs/heads/.+$
claim_pattern:
  job_workflow_ref: ^fohte/tq/\.github/workflows/test\.yml@[^@]+$
repositories:
  - tq
permissions:
  contents: write
