issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fohte/webhook-hub:ref:refs/heads/main$
claim_pattern:
  job_workflow_ref: ^fohte/webhook-hub/\.github/workflows/boilerplate-update\.yml@[^@]+$
repositories:
  - webhook-hub
permissions:
  contents: write
  pull_requests: write
  workflows: write
