issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fohte/webhook-hub:pull_request$
claim_pattern:
  job_workflow_ref: ^fohte/webhook-hub/\.github/workflows/renovate-copier\.yml@[^@]+$
repositories:
  - webhook-hub
permissions:
  contents: write
